# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39721d952b74365a6865f179387ecbd9d49cc55ed75d8fb78d5678ba6aeadc3690fda02101f49ad7e74b827817a5288e679d0f971212ef8ceadc342943752066

test:
  secret_key_base: 18bb272ccbe2e3f48807fc1fbbe1c62a1ce190e170d1cee65073954827c2e97fd8d4932964e388e061b7330abc1ee05717c60d034a620fe16da40b7419f96058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
